
/control/verbose 0
#

/run/verbose 0
#La is 20.85 Bq
#Ac is 5.186567
/run/initialize
/gun/particle ion
/gun/ion 57 138
#La 57 138
/run/beamOn 208500
#1000000 second
/gun/ion 89 227
#Ac 89 227
/run/beamOn 51865

#/tracking/verbose 0
##
#/analysis/setFileName Co60
#/analysis/h1/set 1  150  0. 1500 keV	#e+ e-
#/analysis/h1/set 2  150  0. 1500 keV	#neutrino
#/analysis/h1/set 3  150  0. 1500 keV	#gamma
#/analysis/h1/set 6  100  0. 2500 keV	#EkinTot (Q)
#/analysis/h1/set 7  150  0. 15e3 keV	#P balance
#/analysis/h1/set 8  100  0. 100. year	#time of life
#/analysis/h1/set 9  100  1. 3. MeV  	#EvisTot
##
#/run/printProgress 100000
##  
#/run/beamOn 10
